### ISSUE TITLE
Passing the "buck"

### ISSUE THREAD

**Issue by bgarr33434** [ritchiecarroll/AlexaDo#1]
This looks like the project I have been looking for.  All I want to do (sure) is grab the input request (Literal), build an API call to my AI called SILVIA, pass the query to SILVIA through her API, get a response from SILVIA, and then play the response back through Alexa.  So it would sound like "Alexa, ask SILVIA when my anniversary is", as an example.  I think all I have to do is use the AppLauncher plugin?
 <trigger>
      <keyPhrase>silvia|ask silvia</keyPhrase>
      <matchStyle>StartsWith</matchStyle>
    </trigger>

and modify execute.cs to add the c# code to the public class Execute: to send [query] to SILVIA?

How do I stream back the answer and send to Echo or Dot?

**Comment by bgarr33434** [comment]
"Alexa, Simon Says Google how old is george washington" doesn't seem to be working.  It never shows up in the AlexaDo monitor windows.

**Comment by ritchiecarroll** [comment]
Hi there - this project was an experiment that I developed before Amazon published the API for Echo development. I haven't really looked into it much since the Echo API was released publicly. Is there something in particular you are wanting to accomplish with this project that the Echo API can't do for you?

**Comment by bgarr33434** [comment]
Thanks, Richie.  I liked it because it was local and didn't require publishing a webapp, and it lets me write skills in C#.  I think you are alone in offering those two benefits for the private skill writer (I'm not interested in publishing, just enabling my home!).  So, my goal is simply to be able to say "Alexa, ask SILVIA <intent query that SILVIA will parse and fire the appropriate SILVIA behavior>."  It looks like this will do that, as long as I have AlexaDo windows monitor running on one of my PCs (probably my web hosting machine).  I think the only thing missing is the ability to send the response string (text) back to Alexa to exude as TTS.

I also want to compliment you on excellent documentation.  There are about 20 other C# Alexa Skills packages in GitHub, but almost none of them come with enough documentation for me to get the sample fully operational.  I know, because I spent the holiday weekend trying to get any of the top 5 actually working, to no avail.

**Comment by ritchiecarroll** [comment]
OK then, I'll see if I can get it running again tonight just to make sure everything still works given all the change in the Alexa API's that has happened over last year or so.

FYI, to get get Alexa to use a TTS style response, your host computer needs to connect to Alexa through Bluetooth - when that happens any audio played by the host computer will come back through the Alexa speakers. Note that TTS responses are of course in the local computer voice though. It was Zira, IMO, that was the most similar to Alexa's voice, but you had to install it separately. I haven't looked, but Amazon may have a TTS web service that would playback in Alexa's voice...

**Comment by ritchiecarroll** [comment]
I think I got this back to working now - hope that helps you out!

**Comment by bgarr33434** [comment]
Awesome...thanks!

Brian Garr, COO
Cognitive Code
561.271.4750
@garrbrian
